batch_size: 1
num_workers: 8
infer_overlap: 0.6
learning_rate: 0.0001
max_epochs: 1
sw_batch_size: 2
val_every: 1
weight_decay: 0.00001
solver_name: Adam
pretrained: False
resume: False
exp_name: SegResNet-runs
seed: 123
colab: False
new_max_epochs: None