batch_size: 1
num_workers: 8
fold: 0
infer_overlap: 0.6
learning_rate: 0.0001
max_epochs: 10
pretrained_model: ''
sw_batch_size: 1
val_every: 2
weight_decay: 0.00001
solver_name: Adam
pretrained: False
resume: False
exp_name: SegResNet-runs
seed: 123
colab: False