dataset_file: E:/Brats23 Data/Dataset/BraTS2023_2017_GLI_Mapping.xlsx
json_file: E:/Brats23 Data/Dataset/json_files/dataset.json
test_patient: /all_training_data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData/BraTS-GLI-00016-000
train_path: E:/Brats23 Data/Dataset/all_training_data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData
validation_path: E:/Brats23 Data/Dataset/all_validation_data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData